#!/bin/bash

usage() { echo "$0 usage:" && grep " .)\ #" $0; exit 0; }
post_limit=0
[ $# -eq 0 ] && usage
while getopts ":hd:s:n:r" arg; do
  case $arg in
    d) # default source, used internal.
      default_src=${OPTARG}
      ;;
    n) # number of post limit for generatation.
      post_limit=${OPTARG}
      ;;
    s) # git source utl for the site.
      page=${OPTARG}
      ;;
    r) # run the docker-compose with url.
      web=${OPTARG}
      sudo docker-compose run web -s $web
      exit $?            
    h | *) # Display help.
      usage
      exit 0
      ;;
  esac
done

if [ -z $page ]; then
  git clone $default_src .
else
  git clone $page .
fi

if [[ "$post_limit" -gt 0 ]]; then
  echo -e "\033[1;33m[WARN] Telling jekyll to only generate the last $post_limit posts. \033[0m"
  bundle exec jekyll serve --limit_posts "$post_limit"
else
  bundle exec jekyll serve
fi
